export const FIGLIO_POSITIVO = "figlio.positivo"
export const ALUNNO_POSITIVO = "alunno.positivo"
export const REFERENTE_MANDA_T0_T5 = "referente.manda.t0.t5"
export const T0_TIPO = "t0.tipo"
export const T5_TIPO = "t5.tipo"
export const SERVE_PRESCRIZIONE = "serve.prescrizione"
export const POSSO_RIENTRARE = "posso.rientrare"
export const DOPO_T0 = "dopo.t0"
export const DOPO_T5 = "dopo.t5"
export const SECONDO_POSITIVO = "secondo.positivo"
export const USCITA_QUARANTENA = "uscita.quarantena"
export const BIMBO_48_ORE = "bimbo.48.ore"
export const QUANDO_APPLICHI_QUARANTENA_SORVEGLIANZA = "quando.applichi.quarantena.sorveglianza"
export const SORVEGLIANZA_TESTING = "sorveglianza.testing"
export const SIGNIFICATO_QUARANTENA = "significato.quarantena"


